create table Product
(
    id                 int auto_increment
        primary key,
    publicPrice        decimal(10, 2) not null,
    purchasePrice      decimal(10, 2) not null,
    title              varchar(100)   not null,
    descriptionProduct varchar(1000)  not null,
    brand              int            not null,
    imageURL           varchar(1000)  not null,
    note               varchar(100)   not null,
    constraint FK_Brand_BrandCategory
        foreign key (brand) references Brand (id)
);

INSERT INTO `512Database`.Product (id, publicPrice, purchasePrice, title, descriptionProduct, brand, imageURL, note) VALUES (1, 100.00, 50.00, 'Canon EOS 5D Mark III', 'The Canon EOS 5D Mark III is a full-frame 22.3-megapixel CMOS digital single-lens reflex camera made by Canon. It is the successor to the Canon EOS 5D Mark II, and was announced on 2 September 2012 with a suggested retail price of US$3,799. It was released on 21 November 2012.', 1, 'https://cdn.lesnumeriques.com/optim/produits/1/12892/canon-eos-5d-mark-iii__450_400.jpg', '3.5');
INSERT INTO `512Database`.Product (id, publicPrice, purchasePrice, title, descriptionProduct, brand, imageURL, note) VALUES (2, 100.00, 50.00, 'Canon EOS 5D Mark IV', 'The Canon EOS 5D Mark IV is a full-frame 30.4-megapixel CMOS digital single-lens reflex camera made by Canon. It is the successor to the Canon EOS 5D Mark III, and was announced on 25 August 2016 with a suggested retail price of US$3,799. It was released on 5 September 2016.', 1, 'https://d1fmx1rbmqrxrr.cloudfront.net/cnet/optim/i/edit/2018/08/canon_eos_5DM4_770__w1200.jpg', '3.3');
INSERT INTO `512Database`.Product (id, publicPrice, purchasePrice, title, descriptionProduct, brand, imageURL, note) VALUES (3, 100.00, 50.00, 'Canon EOS 6D Mark II', 'The Canon EOS 6D Mark II is a 26.2-megapixel full-frame CMOS DSLR camera made by Canon. It is the successor to the Canon EOS 6D, and was announced on 16 August 2017 with a suggested retail price of US$1,999. It was released on 17 September 2017.', 1, 'https://cdn.lesnumeriques.com/optim/produits/1/39933/canon-eos-6d-mark-ii-eos-6d-ii_e45659cf38280353__450_400.jpg', '3.3');
INSERT INTO `512Database`.Product (id, publicPrice, purchasePrice, title, descriptionProduct, brand, imageURL, note) VALUES (4, 100.00, 50.00, 'Canon EOS 80D', 'The Canon  EOS 80D Mark II is a 26.2-megapixel full-frame CMOS DSLR camera made by Canon. It is the successor to the Canon EOS 6D, and was announced on 16 August 2017 with a suggested retail price of US$1,999. It was released on 17 September 2017.', 1, 'https://www.canon.fr/for_home/product_finder/cameras/digital_slr/eos-80d/assets/images/360/A_032.png', '5.0');
INSERT INTO `512Database`.Product (id, publicPrice, purchasePrice, title, descriptionProduct, brand, imageURL, note) VALUES (5, 12000.00, 800.00, 'D75000', 'La recherche de l''image parfaite peut vous conduire n''importe où. Emportez avec vous le D7500 puissant, réactif et entièrement connecté. Saisissez la beauté telle que vous la voyez avec la qualité d''image au format DX héritée du D500, l''un des produits phare de Nikon.', 2, 'https://cdn.nikoneurope.com/imported/images/web/EU/products/digital-cameras/dslr/D7500/PPDDs/nikon_dslr_d7500_0022_D7500_18_140_front_category_page--original.png', '4.0');
INSERT INTO `512Database`.Product (id, publicPrice, purchasePrice, title, descriptionProduct, brand, imageURL, note) VALUES (6, 10000.00, 800.00, 'D5600', 'La recherche de l''image parfaite peut vous conduire n''importe où. Emportez avec vous le D5600 puissant, réactif et entièrement connecté. Saisissez la beauté telle que vous la voyez avec la qualité d''image au format DX héritée du D500, l''un des produits phare de Nikon.', 2, 'https://cdn.lesnumeriques.com/optim/produits/31/37149/nikon-d5600_922a27fa523873a4__450_400.webp', '3.8');
INSERT INTO `512Database`.Product (id, publicPrice, purchasePrice, title, descriptionProduct, brand, imageURL, note) VALUES (7, 600.00, 400.00, 'D3400', 'La recherche de l''image parfaite peut vous conduire n''importe où. Emportez avec vous le D3400 puissant, réactif et entièrement connecté. Saisissez la beauté telle que vous la voyez avec la qualité d''image au format DX héritée du D500, l''un des produits phare de Nikon.', 2, 'https://cdn.lesnumeriques.com/optim/focus/news/9/9810/D3400_BK_18_55_VR_frt34l__450_400.webp', '3.4');
INSERT INTO `512Database`.Product (id, publicPrice, purchasePrice, title, descriptionProduct, brand, imageURL, note) VALUES (8, 1000.00, 800.00, 'D5500', 'La recherche de l''image parfaite peut vous conduire n''importe où. Emportez avec vous le D5500 puissant, réactif et entièrement connecté. Saisissez la beauté telle que vous la voyez avec la qualité d''image au format DX héritée du D500, l''un des produits phare de Nikon.', 2, 'https://cdn.lesnumeriques.com/optim/produits/31/37149/nikon-d5600_922a27fa523873a4__450_400.webp', '3.7');
INSERT INTO `512Database`.Product (id, publicPrice, purchasePrice, title, descriptionProduct, brand, imageURL, note) VALUES (10, 800.00, 550.00, 'a6100', 'Immortalisez et partagez vos portraits et moments inoubliables. Avec une qualité d''image et une réactivité épatantes basées sur la technologie du plein format, l''appareil se charge du plus difficile : avec l''a6100, vous ne raterez plus un moment clé.', 3, 'https://www.imaging-resource.com/PRODS/sony-a6100/ZPR-SONY-A6100-BEAUTY.JPG', '4.3');
INSERT INTO `512Database`.Product (id, publicPrice, purchasePrice, title, descriptionProduct, brand, imageURL, note) VALUES (11, 900.00, 600.00, 'a6400', 'L''a6400 offre des performances rapides et une gamme de fonctionnalités dignes d''un modèle plein format tout en restant léger et compact. Images fixes ou films, compositions créatives ou selfies de tous les jours, les images sont superbes et dignes de partage dans tous vos déplacements.', 3, 'https://www.juzaphoto.com/shared_files/recensioni/sony_a6400.jpg', '4.6');
INSERT INTO `512Database`.Product (id, publicPrice, purchasePrice, title, descriptionProduct, brand, imageURL, note) VALUES (12, 1000.00, 650.00, 'a6600', 'L''a6600 réunit toutes les fonctionnalités dont vous pouvez avoir besoin quelles que soient les circonstances : une mise au point automatique rapide, un stabilisateur d''image fiable, une qualité d''image remarquable, une batterie haute capacité et des outils performants pour la réalisation de films 4K HDR (HLG).', 3, 'https://static.photocdn.pt/images/articles/2019/09/06/sony_a6600_review.jpg', '4.5');
INSERT INTO `512Database`.Product (id, publicPrice, purchasePrice, title, descriptionProduct, brand, imageURL, note) VALUES (13, 1000.00, 700.00, 'LUMIX S DC-S5', 'Le LUMIX S5 est un réel concentré de technologies à la fois en photo et en vidéo. Retrouvez la qualité d’un capteur plein format dans un boîtier compact et léger. Le LUMIX S5 est votre nouvel outil de création.', 4, 'https://www.bhphotovideo.com/images/images2500x2500/panasonic_dc_s5mk_lumix_dcs5_mirrorless_digital_1583509.jpg', '3.1');
INSERT INTO `512Database`.Product (id, publicPrice, purchasePrice, title, descriptionProduct, brand, imageURL, note) VALUES (14, 900.00, 500.00, 'LUMIX G DC-G100', 'Image et audio de qualité élevée s’associent à un fonctionnement simple dans un boîtier compact et pratique. Il s''agit de l''appareil photo numérique mono-objectif sans miroir (DSLM) spécialement conçu pour les créateurs de contenu.', 4, 'https://media1.test-achats.be/images/A7A74FD8DEEAC6D450D73A69137E1B3F28802980/c4/Appareils-photo-PANASONIC-LUMIX-DC-G100-plus-LUMIX-G-VARIO-12-32-zoom.jpeg', '3.7');
INSERT INTO `512Database`.Product (id, publicPrice, purchasePrice, title, descriptionProduct, brand, imageURL, note) VALUES (15, 800.00, 600.00, 'LUMIX S DC-S1H', 'Appareil Hybride Plein Format expert cinéma doté de l’enregistrement vidéo 6K 24p, du 4:2:2 10bit en C4K 30p interne, et de la fonction Double ISO natif. Plage dynamique 14+ stops et V-Log/V-Gamut intégrés pour des vidéos de qualité cinématographique.', 4, 'https://www.testatinromania.ro/wp-content/uploads/2019/06/panasonic-lumix-s1h.jpg', '4.2');
INSERT INTO `512Database`.Product (id, publicPrice, purchasePrice, title, descriptionProduct, brand, imageURL, note) VALUES (16, 1100.00, 800.00, 'LUMIX S DC-S1R', 'Un nouveau capteur CMOS 47,3 MP qui permet d''obtenir des détails incroyablement réalistes. Des systèmes de mise au point et de stabilisation d''image qui capturent chaque instant avec une netteté étonnante. L''appareil est conçu pour transformer n''importe quelle idée en photographies inoubliables. Grâce à toutes ces caractéristiques, et bien plus encore, cet appareil photo plein format vous emmène dans le monde extraordinaire de la photographie.', 4, 'https://www.testatinromania.ro/wp-content/uploads/2019/06/panasonic-lumix-s1h.jpg', '3.9');
INSERT INTO `512Database`.Product (id, publicPrice, purchasePrice, title, descriptionProduct, brand, imageURL, note) VALUES (32, 14.40, 12.00, 'test', 'Lorem Ipsumarz', 1, 'zaeaz', '2.5');
